# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-11 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_auto_20180511_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rank',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
