# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-16 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_project_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.ImageField(upload_to=''),
        ),
    ]
