# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-19 09:58
from __future__ import unicode_literals

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0007_auto_20180517_0638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(upload_to=Home.models.project_media_path),
        ),
    ]
