# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 13:18
from __future__ import unicode_literals

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0011_auto_20180526_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(null=True, upload_to=Home.models.project_media_path),
        ),
    ]
