# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_project_youtube_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
