# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-05-28 13:19
from __future__ import unicode_literals

import Home.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_auto_20180528_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to=Home.models.project_media_path),
        ),
    ]
