# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-28 08:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0013_auto_20180528_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='youtube_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
