# Generated by Django 2.0.6 on 2018-09-24 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20180528_1326'),
        ('Home', '0014_auto_20180528_0857'),
    ]

    operations = [
    ]
